// 全局Loading
export const SETLOADING = 'SETLOADING'
export type SETLOADING_TYPE = typeof SETLOADING

//
export const SETPLAYLIST = 'SETPLAYLIST'
export type SETPLAYLIST_TYPE = typeof SETPLAYLIST

export const SET_PLAY_LYRIC = 'SET_PLAY_LYRIC'
export type SET_PLAY_LYRIC_TYPE = typeof SET_PLAY_LYRIC

export const SET_PLAY_MUSIC = 'SET_PLAY_MUSIC'
export type SET_PLAY_MUSIC_TYPE = typeof SET_PLAY_MUSIC

export const SET_LOCAL_MUSIC = 'SET_LOCAL_MUSIC'
export type SET_LOCAL_MUSIC_TYPE = typeof SET_LOCAL_MUSIC

export const SET_PLAY_MUSIC_LOVE = 'SET_PLAY_MUSIC_LOVE'
export type SET_PLAY_MUSIC_LOVE_TYPE = typeof SET_PLAY_MUSIC_LOVE